### ISSUE TITLE
RemoteServiceException Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{67620ab u0 OUR_BRAND/de.idnow.sdk.util.IDnowForegroundService}

### ISSUE THREAD

**Issue by vkuprin** [idnow/de.idnow.android#104]
`android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{67620ab u0 /OUR_BRAND.sdk.util.IDnowForegroundService}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2031)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7499)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)`

**Comment by vkuprin** [comment]
Breadcrums of lifecycle to reproduce:

ui.lifecycle
{
screen: Activities_VideoLiveStreamActivity_IceLink, 
state: created
}
info
11:36:39
ui.lifecycle
{
screen: Activities_VideoLiveStreamActivity_IceLink, 
state: started
}
info
11:36:41
ui.lifecycle
{
screen: Activities_VideoLiveStreamActivity_IceLink, 
state: resumed
}
info
11:36:41
ui.lifecycle
{
screen: Activities_VideoOverviewCheckActivity, 
state: stopped
}
info
11:36:52
ui.lifecycle
{
screen: Activities_VideoOverviewCheckActivity, 
state: saveInstanceState
}
info
11:36:52
exception
RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{67620ab u0 ua.fairo/de.idnow.sdk.util.IDnowForegroundService}
error
