### ISSUE TITLE
ANR in Activities_VideoLiveStreamActivity_IceLink

### ISSUE THREAD

**Issue by dmitry-bystrov** [idnow/de.idnow.android#111]
**Input dispatching timed out (f0b6f51 tech.pnlfin.finom/de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_IceLink (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false))**

```
  at java.lang.UNIXProcess.waitFor (UNIXProcess.java:208)
  at de.idnow.sdk.util.Util_Connectivity.isOnline (Util_Connectivity.java:51)
  at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_IceLink.onResume (Activities_VideoLiveStreamActivity_IceLink.java:689)
```

In some cases it has forced crash which is described in this issues: https://github.com/idnow/de.idnow.android/issues/97 https://github.com/idnow/de.idnow.android/issues/104

**Comment by AlonsoFloo** [comment]
Hello,

Any news on this ?
We are on IDNow 5.1.12 and we are still experiencing this crash as soon as the video stream start

Same stacks
```
main (waiting): tid=1 systid=9177 
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.UNIXProcess.waitFor(UNIXProcess.java:208)
       at de.idnow.sdk.util.Util_Connectivity.isOnline(Util_Connectivity.java:51)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_IceLink.onPause(Activities_VideoLiveStreamActivity_IceLink.java:651)
       at android.app.Activity.performPause(Activity.java:8325)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1544)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5280)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5241)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5188)
```
