### ISSUE TITLE
HTTP method annotation is required - Production

### ISSUE THREAD

**Issue by soheilnikbin** [idnow/de.idnow.android#135]
**Environment:**
Using Android SDK as plugin in Flutter.
SDK Version: `5.1.10`

**SDK Initialization**
```
try {
   String transactionToken = call.argument("transactionToken");
   sdk.initialize(activity, "****");
   IDnowSDK.setTransactionToken(transactionToken, activity);
   IDnowSDK.setShowVideoOverviewCheck(true, activity);
   IDnowSDK.setShowErrorSuccessScreen(true, activity);
   IDnowSDK.setEnvironment(IDnowSDK.Server.LIVE);
   sdk.start(IDnowSDK.getTransactionToken(activity));
   latestRequestResult = result;
} catch (Exception e) {
    result.error("SDK error", e.getLocalizedMessage(), null);
}
```
**Production Error**
```
06-22 15:26:20.929 14210 14210 I IDNOW_RESTCLIENT:  getRestClient()
06-22 15:26:20.930 14210 14210 I IDNOW_RESTCLIENT: SYSTEM-LANGUAGE: en
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: ---- ERROR
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: java.lang.IllegalArgumentException: Network_RESTCalls.getCompanyShortname: HTTP method annotation is required (e.g., @GET, @POST, etc.).
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: 	at gn.n.c(Unknown Source:53)
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: 	at gn.n.f(Unknown Source:271)
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: 	at gn.n.b(Unknown Source:7)
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: 	at gn.m$e.b(Unknown Source:9)
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: 	at gn.m$e.a(Unknown Source:0)
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: 	at gn.m$e$b.b(Unknown Source:8)
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: 	at gn.b.run(Unknown Source:0)
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: 	at gn.g$b$b$a.run(Unknown Source:7)
06-22 15:26:20.931 14210 14627 I IDNOW_RESTCLIENT: 	at java.lang.Thread.run(Thread.java:764)
06-22 15:26:20.932 14210 14627 I IDNOW_RESTCLIENT: ---- END ERROR
06-22 15:26:20.932 14210 14210 E IDNOW   : RETROFIT ERROR: Network_RESTCalls.getCompanyShortname: HTTP method annotation is required (e.g., @GET, @POST, etc.).
```

**Comment by soheilnikbin** [comment]
The problem we encountered with IDNow Android SDK is related to the minify and shrink functions within Gradle files. The assumption is that Gradle considers some classes independent and deletes them at the time of build due to annotation injection in their SDK.
We have provided our solution that fixes the issue to turn off this feature for IDNow SDK that added 8MB to the built application. Please note that this is a temporary solution and needs to be resolved by the IDNow Android team.
```
   buildTypes {
       release {
           minifyEnabled false
           shrinkResources false
           signingConfig signingConfigs.release
       }
   }
```
[On this page,](https://stackoverflow.com/questions/56951296/how-to-protect-classes-from-being-removed-by-minify-enabled) you can find information on how to prevent your classes from being removed when this mode is active.

**Comment by molundb** [comment]
We faced the exact same issue and the solution of @soheilnikbin works. Could be nice to put this in the README perhaps?
