### ISSUE TITLE
Crash - requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by soheilnikbin** [idnow/de.idnow.android#144]
Crashe In Android

> Galaxy S20 FE 5Gaccess_time
> Android 12
> 2 Sept 2022, 10:28:02

Error:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owwn.android.app/de.idnow.sdk.Activities.Activities_VideoOverviewCheckActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4111)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
```
Caused by android.util.AndroidRuntimeException: requestFeature() must be called before adding content
       at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:466)
       at android.app.Activity.requestWindowFeature(Activity.java:5159)
       at de.idnow.sdk.Activities.Activities_VideoOverviewCheckActivity.onCreate(Activities_VideoOverviewCheckActivity.java:179)
       at android.app.Activity.performCreate(Activity.java:8290)
       at android.app.Activity.performCreate(Activity.java:8270)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4085)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by timacosta** [comment]
This happened to me as well after updating to Navigation Component 2.5.1. Here the release notes: 
https://developer.android.com/jetpack/androidx/releases/navigation#2.5.1

**Comment by danielocampo2** [comment]
Thanks @timacosta 

This issue is coming from Lifecycle 2.5.1 (`androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1`) which is being also used by Navigation Component 2.5.1.

The bundled library inside IDNow seems to be 2.3.1 so it should be upgraded to 2.5.1.

**Comment by RicardAparicio** [comment]
For me what fixes the problem was the `androidx.appcompat:appcompat` , upgrading to **1.5.0** or **1.5.1** fixed the issue.
`androidx.appcompat:appcompat:1.5.1`
