### ISSUE TITLE
IllegalStateException on version 5.3.0 [Android]

### ISSUE THREAD

**Issue by DimitarMilushev** [idnow/de.idnow.android#155]
Hello, 
I recently updated to version 5.3.0 from 5.1.12.
However few users with Samsung Galaxy devices have received the following error:
`Fatal Exception: java.lang.IllegalStateException: Insights.sharedInstance().init must be called before accessing sessions
       at de.idnow.insights.Insights.sessions(Insights.java:2640)
       at de.idnow.sdk.Activities.Activities_VideoOverviewCheckActivity.onBackPressed(Activities_VideoOverviewCheckActivity.java:417)
       at android.app.Activity.onKeyUp(Activity.java:3905)
       at android.view.KeyEvent.dispatch(KeyEvent.java:3688)
       at android.app.Activity.dispatchKeyEvent(Activity.java:4230)
       at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:124)
       at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
       at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:142)
       at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:601)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3106)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:823)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7722)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7545)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7176)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7363)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3399)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2960)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2951)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3376)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`
       
I haven't been able to reproduce the exact issue but after identification on Huawei Y6p i do receive the following error:
      `java.lang.RuntimeException: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.`

**Comment by DimitarMilushev** [comment]
Turns out to be caused by pressing back button on Android.
It has been fixed in 6.x.x+ versions, though I couldn't find any concrete fix for those who want to stay at an older version.
