### ISSUE TITLE
6.1.1 NullPointerException 

### ISSUE THREAD

**Issue by sebastianmarschall** [idnow/de.idnow.android#156]
I'm seeing a lot of crashes in version 6.1.1

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getCacheDir()' on a null object reference
       at de.idnow.sdk.util.Util_Util.clearApplicationData(Util_Util.java:923)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super.openResultActivity(Activities_VideoLiveStreamActivity_Super.java:6867)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super.triggerOnBackPressed(Activities_VideoLiveStreamActivity_Super.java:6838)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_IceLink.triggerOnBackPressed(Activities_VideoLiveStreamActivity_IceLink.java:874)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super$94.success(Activities_VideoLiveStreamActivity_Super.java:6079)
       at de.idnow.sdk.network.Callback.onResponse(Callback.java:15)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0(DefaultCallAdapterFactory.java:89)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.$r8$lambda$hVGjmafRi6VitDIrPNdoFizVAdk(DefaultCallAdapterFactory.java)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$InternalSyntheticLambda$1$4ec85956eedcb160a0895cee6bf63a4075ed4f0aeb1d730493e226b7e1834c9f$0.run(DefaultCallAdapterFactory.java:6)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
```

**Comment by hbedekLU** [comment]
We do have this exact same issue as well in production.
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getCacheDir()' on a null object reference
       at de.idnow.sdk.util.Util_Util.clearApplicationData(Util_Util.java:923)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super.openResultActivity(Activities_VideoLiveStreamActivity_Super.java:6867)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super.triggerOnBackPressed(Activities_VideoLiveStreamActivity_Super.java:6838)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_IceLink.triggerOnBackPressed(Activities_VideoLiveStreamActivity_IceLink.java:874)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super$94.success(Activities_VideoLiveStreamActivity_Super.java:6079)
       at de.idnow.sdk.network.Callback.onResponse(Callback.java:15)`

Is there a release already planned to fix this issue ?

**Comment by androideveloper** [comment]
Per IdNow official support, 6.1.3 should have a fix for it

**Comment by sebastianmarschall** [comment]
@androideveloper Unfortunately not. Released an update with 6.1.3 yesterday and seeing the same crashes again. 😞

**Comment by sebastianmarschall** [comment]
@souheib93 is someone looking into this?
