### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for long fm.liveswitch.audioprocessing.Native.AudioProcessingFMCreate

### ISSUE THREAD

**Issue by Renszit** [idnow/de.idnow.android#168]
Hi, 

We are getting the following crash on x86 CPU architecture builds using the IDnow sdk as a native module in a react native project.

Crash occurs after approving microphone and video access. 

```
FATAL EXCEPTION: main
Process: de.product.product, PID: 10860
java.lang.UnsatisfiedLinkError: No implementation found for long fm.liveswitch.audioprocessing.Native.AudioProcessingFMCreate(long, long, long, long, int, int, boolean) (tried Java_fm_liveswitch_audioprocessing_Native_AudioProcessingFMCreate and Java_fm_liveswitch_audioprocessing_Native_AudioProcessingFMCreate__JJJJIIZ)
	at fm.liveswitch.audioprocessing.Native.AudioProcessingFMCreate(Native Method)
	at fm.liveswitch.audioprocessing.Native.<init>(Native.java:17)
	at fm.liveswitch.audioprocessing.AecProcessor.<init>(AecProcessor.java:65)
	at fm.liveswitch.audioprocessing.AecProcessor.<init>(AecProcessor.java:39)
	at de.idnow.sdk.icelink3.AecContext.createProcessor(AecContext.java:16)
	at fm.liveswitch.AecContext.<init>(AecContext.java:25)
	at de.idnow.sdk.icelink3.AecContext.<init>(AecContext.java:10)
	at de.idnow.sdk.icelink3.Conference.<init>(Conference.java:84)
	at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_CallQualityCheck$CallQualityConference.<init>(Activities_VideoLiveStreamActivity_CallQualityCheck.java:2049)
	at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_CallQualityCheck.initConference(Activities_VideoLiveStreamActivity_CallQualityCheck.java:723)
	at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_CallQualityCheck.access$500(Activities_VideoLiveStreamActivity_CallQualityCheck.java:130)
	at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_CallQualityCheck$6.success(Activities_VideoLiveStreamActivity_CallQualityCheck.java:659)
	at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_CallQualityCheck$6.success(Activities_VideoLiveStreamActivity_CallQualityCheck.java:619)
	at de.idnow.sdk.network.Callback.onResponse(Callback.java:15)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by Renszit** [comment]
I have made a small example project here: https://github.com/Renszit/idnow_test . It continues to crash for us on x86 & x86_64 devices.
