### ISSUE TITLE
Cannot get success message from SDK even if the verification process completes successfully. 

### ISSUE THREAD

**Issue by erayasan** [idnow/de.idnow.android#188]
**Description**
Hello! I have integrated IdNow SDK v6.6.0 to my application, but sdk throws RuntimeException when the video call starts. Later, when the “Done” button is clicked after video session ends, it returns to Terms & Conditions page. To return back to my application screen when the back button is clicked the IdNowSDK returns IDnowSDK.RESULT_CODE_CANCEL code. Same behaviour is occuring at the provided sample application too.

**Reproduce steps**

Provide test transaction token to IDnowSDK.setTransactionToken(String) method
Press "Video-identifizierung starten" button
IdNow SDK launches main screen
Press Video-identifizierung starten button
Screen with Terms & Conditions should appear
Start video call
SDK throws RuntimeException without crashing the app
Complete video call
Press Done button
SDK returns terms & Conditions page
Press back button to return back to main calling screen
IdNow SdK return a result that equals to "IDnowSDK.RESULT_CODE_CANCEL"
Reproduced on devices
Samsung Galaxy M51, Android 12
Samsung S7 Edge, Android 6.0

**Stacktrace:**

`E/FM: 2023-05-26T08:19:42.139Z Could not set local view. java.lang.RuntimeException: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first. at fm.liveswitch.android.Utility.dispatchToMainThread(Utility.java:93) at fm.liveswitch.android.Utility.dispatchToMainThread(Utility.java:14) at fm.liveswitch.android.LayoutManager.dispatchToMainThread(LayoutManager.java:104) at fm.liveswitch.LayoutManager.setLocalView(LayoutManager.java:692) at de.idnow.sdk.icelink3.Conference$8.run(Conference.java:517) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:226) at android.os.Looper.loop(Looper.java:313) at android.app.ActivityThread.main(ActivityThread.java:8663) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first. at android.view.ViewGroup.addViewInner(ViewGroup.java:6084) at android.view.ViewGroup.addView(ViewGroup.java:5903) at android.view.ViewGroup.addView(ViewGroup.java:5843) at android.view.ViewGroup.addView(ViewGroup.java:5815) at fm.liveswitch.android.LayoutManager.addView(LayoutManager.java:84) at fm.liveswitch.android.LayoutManager.addView(LayoutManager.java:15) at fm.liveswitch.LayoutManager.setLocalViewUI(LayoutManager.java:716) at fm.liveswitch.LayoutManager.access$600(LayoutManager.java:8) at fm.liveswitch.LayoutManager$9.invoke(LayoutManager.java:697) at fm.liveswitch.android.LayoutManager$2.invoke(LayoutManager.java:108) at fm.liveswitch.android.Utility$1.run(Utility.java:43) at fm.liveswitch.android.Utility.dispatchToMainThread(Utility.java:64) at fm.liveswitch.android.Utility.dispatchToMainThread(Utility.java:14)  at fm.liveswitch.android.LayoutManager.dispatchToMainThread(LayoutManager.java:104)  at fm.liveswitch.LayoutManager.setLocalView(LayoutManager.java:692)  at de.idnow.sdk.icelink3.Conference$8.run(Conference.java:517)  at android.os.Handler.handleCallback(Handler.java:938)  at android.os.Handler.dispatchMessage(Handler.java:99)  at android.os.Looper.loopOnce(Looper.java:226)  at android.os.Looper.loop(Looper.java:313)  at android.app.ActivityThread.main(ActivityThread.java:8663)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

https://github.com/idnow/de.idnow.android/assets/14939183/51933829-5a7e-4c26-bdb3-32060f2f81b0

**Comment by fratt-elca** [comment]
Hello,

A member of Intrum (the company that distributes IDnow in Switzerland) has told us that you received an answer directly from IDnow about your question.

Is this true ? What was their answer ?

Thank you
