### ISSUE TITLE
Crash - IllegalArgumentException in VideoLiveStreamActivity

### ISSUE THREAD

**Issue by mmarkiew** [idnow/de.idnow.android#21]
We are using IdNow SDK in one of our projects. Recently we caught a few crash logs. Below you can find crash log details.

**IdNow SDK Version: 3.4.4**

Problems occurs multiple times o different devices, e.g.:

```
SM-J510FN
Android 7.1.1

SM-G950F
Android 7.0

F8331
Android 8.0.0

WAS-LX1A
Android 7.0

SM-A310F
Android 7.0
```

**Crash Log:**

```
Android: 7.1.1
Android Build: NMF26X.J510FNXXU2BQK6
Manufacturer: samsung
Model: SM-J510FN
Thread: main-1
Start Date: 2018-02-01T09:10:12.329Z
Date: 2018-02-01T09:27:52.071Z

java.lang.IllegalArgumentException
	at android.os.Parcel.readException(Parcel.java:1708)
	at android.os.Parcel.readException(Parcel.java:1654)
	at android.app.ActivityManagerProxy.isTopOfTask(ActivityManagerProxy.java:6674)
	at android.app.Activity.isTopOfTask(Activity.java:6209)
	at android.app.Activity.onResume(Activity.java:1337)
	at de.idnow.sdk.Activities_VideoLiveStreamActivity_Super.onResume(Activities_VideoLiveStreamActivity_Super.java:655)
	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink.onResume(Activities_VideoLiveStreamActivity_IceLink.java:620)
	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink$2$2.run(Activities_VideoLiveStreamActivity_IceLink.java:182)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

```

**Comment by andreaskofer** [comment]
Hello,

can you please re-raise the issue in our support desk tool at https://support.idnow.de as we need more information from you.

Thank you and best regards,
Andreas

**Comment by TimStrietzel** [comment]
Hello @andreaskofer !
In behalf of @mmarkiew I reported the issue to the idnow service desk (DESK-3346).
Cheers!
Tim

**Comment by hendrawd** [comment]
It should be related to https://issuetracker.google.com/issues/66849632
