### ISSUE TITLE
Multiple crashes - View not attached to window manager

### ISSUE THREAD

**Issue by mmarkiew** [idnow/de.idnow.android#22]
We are using IdNow SDK in one of our projects. Recently we caught a few crash logs. Below you can find crash log details.

 **IdNow SDK Version: 3.4.4**

Problems occurs multiple times o different devices, e.g.:
```
F3111
Android 7.0

SM-G935F
Android 7.0

FRD-L09
Android 7.0

SM-G930F
Android 7.0
```

**Crash Logs:**

```
Android: 7.0
Android Build: 33.3.A.1.115
Manufacturer: Sony
Model: F3111
Thread: main-1
Start Date: 2018-02-02T17:41:58.647Z
Date: 2018-02-02T20:50:11.566Z

java.lang.IllegalArgumentException: View=DecorView@75e7f09[] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:497)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:404)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
	at android.app.Dialog.dismissDialog(Dialog.java:367)
	at android.app.Dialog.dismiss(Dialog.java:346)
	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink$5.run(Activities_VideoLiveStreamActivity_IceLink.java:422)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6361)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

  -----------------------

```
Android Build: DK9FA23WTAF.DGE.D7.HB.FHD.SCS8SSX.1107.V3.04
Manufacturer: DOOGEE
Model: Y6 Max
Thread: main-1
Start Date: 2018-02-22T17:25:59.494Z
Date: 2018-03-01T15:44:59.206Z


java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{54ff4ee V.E...... R....... 0,0-1026,567} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:448)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:372)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:372)
	at android.app.Dialog.dismiss(Dialog.java:351)
	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink$5.run(Activities_VideoLiveStreamActivity_IceLink.java:422)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5692)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
```

**Comment by andreaskofer** [comment]
Hello,

can you please re-raise the issue in our support desk tool at https://support.idnow.de as we need more information from you.

Thank you and best regards,
Andreas
