### ISSUE TITLE
IceLinkController crashes - NullPointerException

### ISSUE THREAD

**Issue by mmarkiew** [idnow/de.idnow.android#23]
**IdNow SDK Version: 3.4.4**

Problems occurs multiple times o different devices, e.g.:
```
SM-G935F
Android 7.0

MYA-L41
Android 6.0
```

**Crash logs:**
```
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'void fm.icelink.Conference.receiveOfferAnswer(fm.icelink.OfferAnswer, java.lang.String)' on a null object reference
	at de.idnow.sdk.IceLinkController.receiveOfferAnswer(IceLinkController.java:571)
	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink$12.success(Activities_VideoLiveStreamActivity_IceLink.java:926)
	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink$12.success(Activities_VideoLiveStreamActivity_IceLink.java:878)
	at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void fm.icelink.Conference.receiveOfferAnswer(fm.icelink.OfferAnswer, java.lang.String)' on a null object reference
	at de.idnow.sdk.IceLinkController.receiveOfferAnswer(IceLinkController.java:566)
	... 10 more
```

-------------

```
Android: 7.0
Android Build: NRD90M.G935FXXS1DQL1
Manufacturer: samsung
Model: SM-G935F
Thread: main-1
Start Date: 2018-02-22T14:42:48.287Z
Date: 2018-02-22T14:56:42.337Z

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.addView(android.view.View, android.view.ViewGroup$LayoutParams)' on a null object reference
	at de.idnow.sdk.IceLinkController$11.run(IceLinkController.java:404)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by andreaskofer** [comment]
Hello,

can you please re-raise the issue in our support desk tool at https://support.idnow.de as we need more information from you.

Thank you and best regards,
Andreas

**Comment by TimStrietzel** [comment]
Hello @andreaskofer !
In behalf of @mmarkiew I reported the issue to the idnow service desk (DESK-3347).
Cheers!
Tim
