### ISSUE TITLE
Unable to pause activity crash on VideoLiveStreamActivity

### ISSUE THREAD

**Issue by mmarkiew** [idnow/de.idnow.android#24]
**IdNow SDK Version: 3.4.4**

Problems occurs multiple times on one device devices:
```
BLA-L09
Android 8.0.0
```

Crash log:

```
Android: 8.0.0
Android Build: BLA-L09 8.0.0.128(C432)
Manufacturer: HUAWEI
Model: BLA-L09
Thread: main-1
Start Date: 2018-03-15T14:39:56.710Z
Date: 2018-03-15T14:47:06.451Z

java.lang.RuntimeException: Unable to pause activity {xxx.xxxxxx.xxxxx/de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink}: java.lang.NullPointerException: Attempt to invoke virtual method 'void de.idnow.sdk.IceLinkController.pauseLocalVideo()' on a null object reference
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4542)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4501)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4475)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4443)
	at android.app.ActivityThread.-wrap16(ActivityThread.java:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1893)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7390)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void de.idnow.sdk.IceLinkController.pauseLocalVideo()' on a null object reference
	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink.onPause(Activities_VideoLiveStreamActivity_IceLink.java:590)
	at android.app.Activity.performPause(Activity.java:7518)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1420)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4524)
	... 11 more
```

**Comment by andreaskofer** [comment]
Hello,

can you please re-raise the issue in our support desk tool at https://support.idnow.de as we need more information from you.

Thank you and best regards,
Andreas

**Comment by TimStrietzel** [comment]
Hello @andreaskofer !
In behalf of @mmarkiew I reported the issue to the idnow service desk (DESK-3348).
Cheers!
Tim
