### ISSUE TITLE
IndexOutOfBoundException crash

### ISSUE THREAD

**Issue by mmarkiew** [idnow/de.idnow.android#25]
**IdNow SDK Version: 3.4.4**

Problems occurs multiple times on one device devices:
```
SM-G900F
Android 6.0.1

```

**Crash log**
```
Android: 6.0.1
Android Build: MMB29M.G900FXXS1CQD4
Manufacturer: samsung
Model: SM-G900F
Thread: main-1
Start Date: 2018-03-12T21:31:35.439Z
Date: 2018-03-12T21:58:30.818Z

java.lang.IndexOutOfBoundsException
	at android.view.ViewGroup.removeFromArray(ViewGroup.java:4774)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4959)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4923)
	at android.view.ViewGroup.removeView(ViewGroup.java:4854)
	at de.idnow.sdk.IceLinkController$12.run(IceLinkController.java:450)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by andreaskofer** [comment]
Hello,

can you please re-raise the issue in our support desk tool at https://support.idnow.de as we need more information from you.

Thank you and best regards,
Andreas

**Comment by TimStrietzel** [comment]
Hello @andreaskofer !
In behalf of @mmarkiew I reported the issue to the idnow service desk (DESK-3349).
Cheers!
Tim

**Comment by burakozhan** [comment]
Try disabling instantrun.
