### ISSUE TITLE
NoClassDefFoundError in 3.9.2 (de/idnow/sdk/Network_OkHttpWebSocket)

### ISSUE THREAD

**Issue by suzukieng** [idnow/de.idnow.android#26]
Phone: Samsung Galaxy S7
OS: Android 7.0
IDnow SDK version: 3.9.2 (latest at time of writing)

After starting video identification, the user is prompted for permissions. After both permissions (camera and record audio) are granted, the app crashes with a NoClassDefFoundError.

```
--------- beginning of crash
06-21 09:34:01.795 17941 17941 E AndroidRuntime: FATAL EXCEPTION: main
06-21 09:34:01.795 17941 17941 E AndroidRuntime: Process: ch.hin.hinvideoident, PID: 17941
06-21 09:34:01.795 17941 17941 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lde/idnow/sdk/Network_OkHttpWebSocket;
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.Activities_VideoLiveStreamActivity_Super.startWebsocket(Activities_VideoLiveStreamActivity_Super.java:725)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.Activities_VideoLiveStreamActivity_Super.setupConnection(Activities_VideoLiveStreamActivity_Super.java:717)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink$4.invoke(Activities_VideoLiveStreamActivity_IceLink.java:439)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink$4.invoke(Activities_VideoLiveStreamActivity_IceLink.java:428)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.LocalMedia$1$2.invoke(LocalMedia.java:105)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.LocalMedia$1$2.invoke(LocalMedia.java:74)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.UserMedia.raiseGetMediaSuccess(UserMedia.java:220)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.UserMedia.localStreamStartSuccess(UserMedia.java:123)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.UserMedia.access$100(UserMedia.java:6)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.UserMedia$2.invoke(UserMedia.java:147)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.UserMedia$2.invoke(UserMedia.java:142)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.LocalMediaStream.raiseStartSuccess(LocalMediaStream.java:463)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.LocalMediaStream.startVideoSuccess(LocalMediaStream.java:803)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.LocalMediaStream.startVideo(LocalMediaStream.java:783)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.LocalMediaStream.startAudioSuccess(LocalMediaStream.java:763)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.LocalMediaStream.startAudio(LocalMediaStream.java:742)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.LocalMediaStream.start(LocalMediaStream.java:717)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.UserMedia.onLocalStreamInitialize(UserMedia.java:169)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.UserMedia.access$000(UserMedia.java:6)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.UserMedia$1.invoke(UserMedia.java:83)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.UserMedia$1.invoke(UserMedia.java:78)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.LocalMediaStream.initialize(LocalMediaStream.java:313)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at fm.icelink.webrtc.UserMedia.getMedia(UserMedia.java:77)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.LocalMedia.getMedia(LocalMedia.java:44)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.LocalMedia.start(LocalMedia.java:123)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.IceLinkController.startLocalMedia(IceLinkController.java:315)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.IceLinkController.startLocalMedia(IceLinkController.java:308)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink.startLocalMedia(Activities_VideoLiveStreamActivity_IceLink.java:427)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink.sessionConnect(Activities_VideoLiveStreamActivity_IceLink.java:1037)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink.onCreate(Activities_VideoLiveStreamActivity_IceLink.java:255)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6912)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6692)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: de.idnow.sdk.Network_OkHttpWebSocket
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	... 42 more
06-21 09:34:01.795 17941 17941 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/WebSocketListener;
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	... 42 more
06-21 09:34:01.795 17941 17941 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.WebSocketListener" on path: DexPathList[[zip file "/data/app/ch.hin.hinvideoident-1/base.apk"],nativeLibraryDirectories=[/data/app/ch.hin.hinvideoident-1/lib/arm64, /data/app/ch.hin.hinvideoident-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-21 09:34:01.795 17941 17941 E AndroidRuntime: 	... 42 more
```

Gradle dependencies are set according to the documentation, with the SDK AAR residing in the lib s directory.

```
    implementation 'de.idnow.sdk:idnow-android-3.9.2@aar'
    implementation 'com.google.code.gson:gson:2.4'
    implementation 'com.squareup.retrofit:retrofit:1.9.0'
    implementation 'com.squareup.okhttp3:okhttp:3.4.1'
    implementation 'com.squareup.okhttp3:okhttp-ws:3.4.1'
```

**Comment by suzukieng** [comment]
ProGuard is not enabled.

**Comment by andreaskofer** [comment]
Hello,

you can have a look at the gradle file of our sample Android project here https://github.com/idnow/de.idnow.android-sample/blob/master/app/build.gradle

Please try to use the following dependencies within your gradle file:

```
    compile 'de.idnow.sdk:idnow-android-3.9.2@aar'
    // transitive dependencies of the idnow SDK
    compile 'org.slf4j:slf4j-android:1.7.12'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp3:okhttp:3.8.1'
    compile 'com.googlecode.libphonenumber:libphonenumber:8.4.2'

```

Thank you and best regards,
Andreas

**Comment by suzukieng** [comment]
Hi @andreaskofer

Thanks, that solved the problem. Probably an update of the relevant section of README.md is in order.

Kind Regards
Alex

**Comment by andreaskofer** [comment]
Hello Alex,

thanks for your feedback. Yes, the update to the documentation is already on it's way.

Best regards,
Andreas
