### ISSUE TITLE
IceLinkController NPE on removing all views

### ISSUE THREAD

**Issue by kjurkovic** [idnow/de.idnow.android#28]
Device SM-G950F 
OS: Android 8.0.0

Happens after the video ID is completed only when setShowErrorSuccessScreen on SDK is set to false: `IDnowSDK.setShowErrorSuccessScreen(false, this);` 

`FATAL EXCEPTION: main
    Process: de.smava.app.stage.dev, PID: 15831
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RelativeLayout.removeAllViews()' on a null object reference
        at de.idnow.sdk.IceLinkController$14.run(IceLinkController.java:569)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by kbarzen-idn** [comment]
Hello,

could you please use our Service Desk tool at https://support.idnow.de as this will allow us to distribute your question within our team.

Thank you and kind regards,
Kay
