### ISSUE TITLE
Android - Video identification crashes on x86 ABI arch

### ISSUE THREAD

**Issue by rafaelaguerra** [idnow/de.idnow.android#34]
I've this problem with video auth on x86 ABI arch in android.
I'm using 3.17.1 version of IDNow

```
2019-05-22 16:41:08.614 20478-20562/... E/linker: "/data/app/...-NT_JTZ8sJgvpY-iR1ilOnw==/lib/x86/libvpx.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
2019-05-22 16:41:08.630 20478-20562/task E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: ...task, PID: 20478
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/....-NT_JTZ8sJgvpY-iR1ilOnw==/lib/x86/libvpx.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.google.libvpx.LibVpxCom.<clinit>(LibVpxCom.java:17)
        at avp8.Encoder.encode(Encoder.java:107)
        at avp8.Vp8Codec.encode(Vp8Codec.java:85)
        at fm.icelink.webrtc.VideoCodec.encodeInternal(VideoCodec.java:70)
        at fm.icelink.webrtc.VideoBuffer.encode(VideoBuffer.java:207)
        at fm.icelink.webrtc.MediaStreamTrack.onVideoFrameCaptured(MediaStreamTrack.java:850)
        at fm.icelink.webrtc.MediaStreamTrack.access$100(MediaStreamTrack.java:6)
        at fm.icelink.webrtc.MediaStreamTrack$2.invoke(MediaStreamTrack.java:470)
        at fm.icelink.webrtc.MediaStreamTrack$2.invoke(MediaStreamTrack.java:465)
        at fm.icelink.webrtc.VideoCaptureProvider.raiseFrame(VideoCaptureProvider.java:418)
        at fm.icelink.webrtc.VideoCaptureProvider.raiseFrame(VideoCaptureProvider.java:428)
        at fm.icelink.webrtc.AndroidVideoCaptureProvider.onBufferCaptured(AndroidVideoCaptureProvider.java:292)
        at fm.video.AndroidCapturer$4.run(AndroidCapturer.java:550)
```

**Comment by rafaelaguerra** [comment]
Stopped supported on 2.8.2

**Comment by NazarYablonskiy** [comment]
same with 3.18.0
