### ISSUE TITLE
NoClassDefFoundError 3.22.0

### ISSUE THREAD

**Issue by MarcoGuapi** [idnow/de.idnow.android#41]
help I get this error when starting a video identification when checking the connection quality.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.idnow.sampleproject, PID: 19632
    java.lang.NoClassDefFoundError: de.idnow.sdk.Activities_VideoLiveStreamActivity_Super
        at de.idnow.sdk.IceLinkController$12.run(IceLinkController.java:446)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by aare-undo-idnow** [comment]
I apologise your issue wasn't addressed, however, this has been fixed for some time now. So, closing...
