### ISSUE TITLE
fm.icelink.vpx link error

### ISSUE THREAD

**Issue by daemontus** [idnow/de.idnow.android#54]
Hi, with the latest 4.1.1 release, there is a problem with the included native libraries:

```
E/FM: 2020-02-18T09:58:20.732Z Unable to load vpxfmJNI.  Message: dalvik.system.PathClassLoader[DexPathList[[zip file “/data/app/com.own360.app-1/base.apk”],nativeLibraryDirectories=[/data/app/com.own360.app-1/lib/arm, /vendor/lib, /system/lib]]] couldn’t find “libvpxfmJNI.so”
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.own360.app, PID: 3279
    java.lang.UnsatisfiedLinkError: No implementation found for long fm.icelink.vpx.Native.VpxFMDecoderCreate(long, long, long, long) (tried Java_fm_icelink_vpx_Native_VpxFMDecoderCreate and Java_fm_icelink_vpx_Native_VpxFMDecoderCreate__JJJJ)
        at fm.icelink.vpx.Native.VpxFMDecoderCreate(Native Method)
        at fm.icelink.vpx.Native.<init>(Native.java:86)
        at fm.icelink.vpx.Decoder.<init>(Decoder.java:19)
        at fm.icelink.vp8.Decoder.<init>(Decoder.java:15)
        at de.idnow.sdk.icelink3.RemoteMedia.createVp8Decoder(RemoteMedia.java:88)
        at fm.icelink.RtcRemoteMedia.initialize(RtcRemoteMedia.java:1417)
        at fm.icelink.RtcRemoteMedia.initialize(RtcRemoteMedia.java:1271)
        at de.idnow.sdk.icelink3.RemoteMedia.<init>(RemoteMedia.java:38)
        at de.idnow.sdk.icelink3.Conference.createConnection(Conference.java:183)
        at de.idnow.sdk.icelink3.Conference.<init>(Conference.java:82)
        at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_CallQualityCheck$CallQualityConference.<init>(Activities_VideoLiveStreamActivity_CallQualityCheck.java:1337)
        at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_CallQualityCheck.initConference(Activities_VideoLiveStreamActivity_CallQualityCheck.java:508)
        at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_CallQualityCheck.access$400(Activities_VideoLiveStreamActivity_CallQualityCheck.java:72)
        at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_CallQualityCheck$6.success(Activities_VideoLiveStreamActivity_CallQualityCheck.java:453)
        at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_CallQualityCheck$6.success(Activities_VideoLiveStreamActivity_CallQualityCheck.java:423)
        at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

When we switch back to 4.1.0, the issue is not there.

**Comment by GabrielePrestifilippo** [comment]
The same happened to me with the latest `4.1.4`
