### ISSUE TITLE
App Crash due to android.view.WindowManager$BadTokenException during enable/disable WiFi

### ISSUE THREAD

**Issue by harrymu** [idnow/de.idnow.android#55]
We get the following error (app crash) with version 4.1.1

```
Caused by: android.view.WindowManager$BadTokenException: 
  at android.view.ViewRootImpl.setView (ViewRootImpl.java:792)
  at android.view.WindowManagerGlobal.addView (WindowManagerGlobal.java:373)
  at android.view.WindowManagerImpl.addView (WindowManagerImpl.java:114)
  at android.app.Dialog.show (Dialog.java:445)
  at de.idnow.sdk.MyReceiver.onReceive (MyReceiver.java:28)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3177)
```

The problem is reproducible as follows:
1. Open the app without calling IDnowSDK.getInstance().initialize
2. Press the Home Button
3. Disable WLAN

It seems to occur mainly on devices without a SIM card. 

I can work around this problem by removing MyReceiver:
`<receiver android:name="de.idnow.sdk.MyReceiver" tools:node="remove" />`

Does this have any negative impact on the identification process?

**Comment by TomorrowAndroid** [comment]
Still happens in 4.1.3 please fix:

` java.lang.RuntimeException: Unable to start receiver de.idnow.sdk.MyReceiver: android.view.WindowManager$BadTokenException: Unable to add window -- token null for displayid = 0 is not valid; is your activity running?
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4005)
        at android.app.ActivityThread.access$2300(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2050)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null for displayid = 0 is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:936)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:398)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:131)
        at android.app.Dialog.show(Dialog.java:531)
        at de.idnow.sdk.MyReceiver.onReceive(MyReceiver.java:28)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3996)`

**Comment by joaoSampaio** [comment]
I had the same problem in production (4.1.3), it was fixed in 4.1.4.

**Comment by mtidnow** [comment]
The issue was fixed with version 4.1.4.

**Comment by vikass03** [comment]
Hi: yes issue is fixed in version 4.1.4.
