### ISSUE TITLE
A lot of RuntimeExceptions

### ISSUE THREAD

**Issue by winstonvk** [idnow/de.idnow.android#69]
We use 4.3.4 version of id now
We have a lot of bugs on production:
1) 
```
Fatal Exception: java.lang.RuntimeException: Camera is being used after Camera.release() was called
       at android.hardware.Camera._stopPreview(Camera.java)
       at android.hardware.Camera.stopPreview(Camera.java:839)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super.closeCamera(Activities_VideoLiveStreamActivity_Super.java:4077)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super.switchCamera(Activities_VideoLiveStreamActivity_Super.java:5356)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super.setRightScreen(Activities_VideoLiveStreamActivity_Super.java:1578)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super$31.success(Activities_VideoLiveStreamActivity_Super.java:2194)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super$31.success(Activities_VideoLiveStreamActivity_Super.java:2103)
       at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```
2)
```
Fatal Exception: java.lang.RuntimeException: Camera is being used after Camera.release() was called
       at android.hardware.Camera.startPreview(Camera.java)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super.setRightScreen(Activities_VideoLiveStreamActivity_Super.java:1442)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super$33.success(Activities_VideoLiveStreamActivity_Super.java:2359)
       at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7814)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
```
3)
```
Fatal Exception: java.lang.RuntimeException: takePicture failed
       at android.hardware.Camera.native_takePicture(Camera.java)
       at android.hardware.Camera.takePicture(Camera.java:1614)
       at android.hardware.Camera.takePicture(Camera.java:1554)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super$28.onAutoFocus(Activities_VideoLiveStreamActivity_Super.java:1917)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1277)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6831)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
```
4)
```
Fatal Exception: java.lang.RuntimeException: Camera is being used after Camera.release() was called
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:2189)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super$23.onClick(Activities_VideoLiveStreamActivity_Super.java:1753)
       at android.view.View.performClick(View.java:6659)
       at android.view.View.performClickInternal(View.java:6631)
       at android.view.View.access$3100(View.java:790)
       at android.view.View$PerformClick.run(View.java:26187)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

When will you be able to fix it?

**Comment by winstonvk** [comment]
Ping @souheib93
