### ISSUE TITLE
Models_Sentry.NullPointerException

### ISSUE THREAD

**Issue by nuriking** [idnow/de.idnow.android#70]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'de.idnow.sdk.models.Models_Sentry de.idnow.sdk.models.Models_Settings.getSentry()' on a null object reference
       at de.idnow.sdk.Activities.Activities_EntryActivity$6.success(Activities_EntryActivity.java:631)
       at de.idnow.sdk.Activities.Activities_EntryActivity$6.success(Activities_EntryActivity.java:581)
       at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
       at android.os.Handler.handleCallback(Handler.java:914)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by nuriking** [comment]
operating system Android 10
bug in: 
Galaxy S10+
Galaxy A51
Galaxy S9

**Comment by nuriking** [comment]
today we have new bug on 
- OnePlus 6
- Galaxy Note20 Ultra 5G
- Galaxy S9
- Galaxy S7
and one mobile in Android  OS 8

**Comment by acollazomayer** [comment]
I have the same error, Where you able to fix it @nuriking

**Comment by nuriking** [comment]
updated the library version to 5.0.2

**Comment by acollazomayer** [comment]
Ohh, that is bad, I am in that version....

**Comment by aare-undo-idnow** [comment]
Interesting issue, but fortunately we threw Sentry out a couple of releases back (5.1.5, maybe?) and this is no longer relevant. Closing.
