### ISSUE TITLE
 Error inflating class android.widget.ImageView android.app.ActivityThread.performLaunchActivity

### ISSUE THREAD

**Issue by nuriking** [idnow/de.idnow.android#72]
Mobile LGE Nexus 4 Os 6.0.1

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{tech.pnlfin.finom/de.idnow.sdk.Activities.Activities_EntryActivity}: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class android.widget.ImageView
android.app.ActivityThread.performLaunchActivity

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{tech.pnlfin.finom/de.idnow.sdk.Activities.Activities_EntryActivity}: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class android.widget.ImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by nuriking** [comment]
SDK version 4.3.4
