### ISSUE TITLE
License.java line 95

### ISSUE THREAD

**Issue by nuriking** [idnow/de.idnow.android#74]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{tech.pnlfin.finom/de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_IceLink}: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.Exception: License key not set.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3318)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7555)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
       
Honor 8X , OS Android 8.1.0

**Comment by givehug** [comment]
up

**Comment by givehug** [comment]
We had this issue for a few days, it went away on its own, and now started again.
