### ISSUE TITLE
RuntimeException startPreview failed

### ISSUE THREAD

**Issue by imetodieva** [idnow/de.idnow.android#77]
**Brand: HUAWEI
Model: P20 Pro
OS Version: 10**

Fatal Exception: java.lang.**RuntimeException**: startPreview failed
       at android.hardware.Camera.startPreviewInner(Camera.java)
       at android.hardware.Camera.startPreview(Camera.java:884)
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super$7.onClick(Activities_VideoLiveStreamActivity_Super.java:816)
       at android.view.View.performClick(View.java:7192)
       at android.view.View.performClickInternal(View.java:7166)
       at android.view.View.access$3500(View.java:824)
       at android.view.View$PerformClick.run(View.java:27592)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by aare-undo-idnow** [comment]
I apologise that your issue wasn't addressed earlier, but I'm glad to tell you this has been fixed as of v5.1.5
