### ISSUE TITLE
de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super$73.failure (Activities_VideoLiveStreamActivity_Super.java:4720)

### ISSUE THREAD

**Issue by nuriking** [idnow/de.idnow.android#78]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int retrofit.client.Response.getStatus()' on a null object reference
       at de.idnow.sdk.Activities.Activities_VideoLiveStreamActivity_Super$73.failure(Activities_VideoLiveStreamActivity_Super.java:4720)
       at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7582)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

moto g(8) plus, android 10,

**Comment by nuriking** [comment]
version idNow used 5.0.1
