### ISSUE TITLE
UnsatisfiedLinkError in IDNow SDK 2.10.0

### ISSUE THREAD

**Issue by omkarpn26** [idnow/de.idnow.android#9]
IDNow SDK when used alongside Realm SDK (native) keeps giving the following UnsatisfiedLinkError even after excluding the correct lib architecture directories to match both SDKs. Excluding specific files instead of the entire folder also does not work.

The packaged apk file has the correct folder config i.e. both the SDKs have matching
architecture folders, but the error still remains.

```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.google.a.a.a() (tried Java_com_google_a_a_a and Java_com_google_a_a_a__)
      at com.google.libvpx.LibVpxCom.vpxCodecVersionStr(LibVpxCom.java)
      at com.google.libvpx.LibVpxCom.vpxCodecErrorDetail(LibVpxCom.java:39)
      at de.idnow.sdk.Activities_VideoLiveStreamActivity_IceLink.onCreate(Activities_VideoLiveStreamActivity_IceLink.java:99)
      at android.app.Activity.performCreate(Activity.java:6679)
```

**Comment by hkretzschmar** [comment]
Hi omkarpn26,

can you give us some more details, like the architecture you are trying to link to? 
The exception you get is a little strange in a way because the code that loads the library is guarded with a try catch block that prints out that the corresponding lib has not been found.

From what you send this is not happening. Do you see something like "Unable to read libvpx" in th e logs?

Kind regard
Holger Kretzschmar

**Comment by hkretzschmar** [comment]
Hi omkarpn26,

as an afterthought, would it be possible for you to post your build.gradle file for us to understand how the library structure was set up.

Thanks
Holger Kretzschmar

**Comment by omkarpn26** [comment]
Hi Holger,

Thanks for your reply. Please find the build.gradle file for the project. This is for IDNow SDK version 2.8.0 which works when the **arm64-v8a** and **mips** lib folders are excluded.

For version 2.10.0, we tried excluding **mips** and **x86_64**, which packages the apk properly (there aren't any mismatched folders in libs), but that doesn't work and we get the crash as mentioned above.

```
/* Build Script */
buildscript {
    repositories {
        jcenter()

        maven { url 'https://maven.fabric.io/public' }
        maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
    }

    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'io.fabric.tools:gradle:1.21.6'
        classpath 'io.realm:realm-gradle-plugin:0.88.0'
    }

    // Exclude the version that the android plugin depends on.
    configurations.classpath.exclude group: 'com.android.tools.external.lombok'
}

/* Application */
apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'io.fabric'
apply plugin: 'realm-android'


/* Code Quality */
apply from: "$rootProject.projectDir/config/checkstyle.gradle"
apply from: "$rootProject.projectDir/config/jacoco.gradle"

def getGitHash = { ->
    def stdout = new ByteArrayOutputStream()
    exec {
        commandLine 'git', 'rev-parse', '--short', 'HEAD'
        standardOutput = stdout
    }
    return stdout.toString().trim()
}

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'

    productFlavors {
        dev {
            versionName version + " DEV"
            minSdkVersion 19
        }

        qa {
            versionName version + " QA"
            minSdkVersion 19
        }

        prod {
            minSdkVersion 19
        }
    }

    defaultConfig {
        applicationId "de.number26.android"

        versionCode 107
        versionName "3.1.1"

        targetSdkVersion 25
        multiDexEnabled = true

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    if (System.getenv("STORE_FILE")) {
        signingConfigs {
            release {
                storeFile file(System.getenv("STORE_FILE"))
                storePassword System.getenv("STORE_PASSWORD")
                keyAlias System.getenv("KEY_ALIAS")
                keyPassword System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled true
            shrinkResources true

            proguardFile 'proguard-android.txt'

            if (System.getenv("STORE_FILE")) {
                signingConfig signingConfigs.release
            }
        }
    }

    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets', 'src/main/assets/', 'src/main/assets/fonts']
            jniLibs.srcDirs = ['jniLibs']
        }

        // Makes commonTest classes common for Unit and Functional tests
        def commonTestDir = 'src/commonTest/java'
        test {
            java.srcDir commonTestDir
        }
        androidTest {
            java.srcDir commonTestDir
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    packagingOptions {
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/maindexlist.txt'
        exclude 'META-INF/services/javax.annotation.processing.Processor'
        exclude 'META-INF/maven/com.squareup/javawriter/pom.properties'
        exclude 'META-INF/maven/com.squareup/javawriter/pom.xml'

        exclude "lib/arm64-v8a/libopentok.so"
        exclude "lib/arm64-v8a/librealm-jni.so"
        exclude "lib/mips/librealm-jni.so"
    }

    testOptions {
        unitTests.all {
            jvmArgs '-noverify'
        }
    }
}

repositories {
    maven { url 'https://jitpack.io' }
    maven { url 'https://maven.fabric.io/public' }
    maven { url 'http://maven.snplow.com/releases' }

    // User from IDnow
    maven { url "http://tokbox.bintray.com/maven" }

    flatDir {
        dirs 'libs'
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:design:25.0.1'
    compile 'com.android.support:support-v13:25.0.1'
    compile 'com.android.support:support-annotations:25.0.1'
    androidTestCompile 'com.android.support:support-annotations:25.0.1'
    compile 'com.android.support:cardview-v7:25.0.1'
    compile 'com.android.support:recyclerview-v7:25.0.1'
    compile 'com.android.support:percent:25.0.1'

    compile 'com.google.android.gms:play-services-analytics:10.0.0'
    compile 'com.google.android.gms:play-services-location:10.0.0'
    compile 'com.google.android.gms:play-services-maps:10.0.0'
    compile 'com.google.android.gms:play-services-gcm:10.0.0'
    compile 'com.google.maps.android:android-maps-utils:0.4.1'

    compile 'com.google.dagger:dagger:2.7'
    apt 'com.google.dagger:dagger-compiler:2.7'

    compile 'com.google.code.gson:gson:2.7'

    compile('de.keyboardsurfer.android.widget:crouton:1.8.5@aar') {
        exclude group: 'com.google.android', module: 'support-v4'
    }

    compile 'com.squareup:android-times-square:1.6.4@aar'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okio:okio:1.10.0'
    testCompile 'com.squareup.okio:okio:1.10.0'

    compile 'com.getbase:floatingactionbutton:1.10.1'
    compile 'com.github.chrisbanes.photoview:library:1.2.2'
    compile 'com.github.JakeWharton:ViewPagerIndicator:2.4.1'
    compile 'com.github.kassim:MaterialPatternllockView:1.0.0'
    compile 'com.github.castorflex.smoothprogressbar:library:1.0.0'
    compile 'com.splitwise:tokenautocomplete:2.0.7@aar'
    compile 'com.miguelcatalan:materialsearchview:1.4.0'

    compile 'io.reactivex:rxjava:1.2.0'
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'com.trello:rxlifecycle:0.6.1'
    compile 'com.trello:rxlifecycle-components:0.6.1'
    compile 'com.jakewharton.rxbinding:rxbinding:0.4.0'
    compile 'com.jakewharton.rxrelay:rxrelay:1.1.0'
    compile 'com.tbruyelle.rxpermissions:rxpermissions:0.7.0@aar'

    compile 'net.danlew:android.joda:2.8.2'
    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
    compile 'uk.co.chrisjenx:calligraphy:2.2.0'

    // IDnow
    compile 'de.number26.android:idnow-android-2.8.0@aar'
    compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile 'com.squareup.okhttp3:okhttp-ws:3.4.1'
    compile 'com.opentok.android:opentok-android-sdk:2.9.+'

    compile(project(':core')) {
        exclude module: 'json'
        exclude module: 'joda-time'
    }

    // Video view library - used for the animation videos (mp4)
    compile 'com.github.mklimek:frame-video-view:1.3.1'

    compile project(':adjust')
    compile project(':PushIOManager')

    // Tracking
    compile 'com.snowplowanalytics:snowplow-android-tracker:0.6.+@aar'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.2@aar') { transitive = true; }

    apt 'me.tatarka:auto-parcel-gson-processor:0.2'

    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:1.10.19'
    testCompile 'org.robolectric:robolectric:3.0'
    testCompile 'org.robolectric:shadows-multidex:3.0'
    testCompile 'com.squareup.okhttp3:mockwebserver:3.4.1'

    androidTestCompile 'junit:junit:4.12'
    androidTestCompile 'com.google.code.findbugs:jsr305:3.0.1'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
    androidTestCompile 'com.android.support.test:runner:0.5'

    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5'
    testCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'
}

retrolambda {
    javaVersion JavaVersion.VERSION_1_7
    jvmArgs '-noverify'
}
```

**Comment by hkretzschmar** [comment]
Hi Omar,

so the file you posted is a working case against the older 2.8.0 sdk? I'm still not sure which architectures you need to support, but what I see in your build.gradle is that you try to exclude specific libraries instead of the complete architecture e.g.

**only excludes specific libs**
```
packagingOptions {
        exclude "lib/arm64-v8a/librealm-jni.so"
        exclude "lib/arm64-v8a/libopentok.so"
        exclude "lib/mips/librealm-jni.so"
    }
```

**excludes the whole architecture**
```
packagingOptions {
        exclude "lib/arm64-v8a/"
    }
```

What i suggest is that you make a list of all architectures you support with your 3rd party lib (realm) and compare that to the architectures supported by IDnow which are:

- arm64-v8a
- armeabi-v7a
- armeabi
- x86 

What you need to make sure is that the architectures between your 3rd party lib and IDnow match. The reason for this is that Android uses one and only one of the architectures at runtime. The problem with that is that even if you provide a library for the most generic architecture armeabi this library will not be found if the selected architecture is armeabi-v7a.

As a workaround (only if no other option applies) you could copy the IDnow libs from the most generic version to the architecture you need to support with your 3rd party lib. 

Kind regards
Holger Kretzschmar

**Comment by omkarpn26** [comment]
Hi Holger,

Realm currently supports the following architectures - 

- arm64-v8a
- armeabi-v7a
- armeabi
- x86
- x86_64
- mips

In order to match supported architectures, I tried excluding lib/x86_64/ and lib/mips/ as follows - 
```
packagingOptions {
        exclude "lib/x86_64/"
        exclude "lib/mips/"
}
```

Devices - Nexus 5, Nexus 5x, Google Pixel

I still get the crash as mentioned above on IDNow SDK **2.10.0**. However, with IDNow SDK **2.11.0**, it works without any problems. We'll be using 2.11.0 in our project, so you can close this issue.

Just wanted to give you an update about the same. Thanks for your prompt responses.

Regards,
Omkar

**Comment by hkretzschmar** [comment]
Hi Omkar,

I'm glad that this is working now for you. All the same I'm wondering that the newer version sloved the problem since I can't recall that we changed something significant regarding the 3rd party libs.

All the best
Holger
