### ISSUE TITLE
 Android 8.0.0 Crash - Fatal Exception: android.app.RemoteServiceException

### ISSUE THREAD

**Issue by nuriking** [idnow/de.idnow.android#97]
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1881)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
      
samsung s9 plus

**Comment by vkuprin** [comment]
Seems I faced the same -> https://github.com/idnow/de.idnow.android/issues/104
